AT_025.005 | Header > Verify user will be redirected to new url "users/sign"
RedRoverSchool/OpenWeatherJS_05 pull request #161
Opened 2022-11-15 16:39 UTC by Vik1975

Edit script according to comments.

2022-11-15 17:16 UTC, Vik1975 commented
https://trello.com/c/6jX8R7Ny/142-at025005-main-menu-dashboard-verify-the-first-button-try-the-dashbord-is-clickable-and-redirect-user-to-new-url-users-signin

2022-11-15 17:48 UTC, alena-resh approved these changes

2022-11-15 18:52 UTC, tatsiana-yakimovich requested changes
Please address the comments that I just posted

2022-11-15 18:52 UTC, tatsiana-yakimovich commented on cypress/e2e/jScript_group.cy.js
> +    it('AT_033.007 | Header > Navigation >> Verify "Pricing" menu link', () => {
There are multiple problems here:
1. Don't use cy.visit('https://openweathermap.org') in your tests as we already doing it in beforeEach
2. AT_033.007 code is duplicated and not related to your merge. Probably, some merge conflict issue and you need to remove it.
3. Line 220 - you don't need those closing bracers

2022-11-15 19:31 UTC, TimothyHuxx commented on cypress/e2e/jScript_group.cy.js
> +    it('AT_033.007 | Header > Navigation >> Verify "Pricing" menu link', () => {
@tatsiana-yakimovich Great comment. I would recommend requesting changes instead of writing a simple comment.

2022-11-15 19:38 UTC, TimothyHuxx requested changes
Why you deleted the test from lines 79-83? We don't delete tests. If we need to delete something we should create refactor card and do it separately.  
Also, there are two empty lines 78 and 79.
We add only one test in each PR

2022-11-16 02:11 UTC, TimothyHuxx commented
@Vik1975 Got it. You still have a few issues. Please review the comment from tatsiana-yakimovich

2022-11-16 03:25 UTC, Vik1975 commented
@tatsiana-yakimovich Seems to have fixed everything. Could you check it please.

2022-11-16 04:53 UTC, tatsiana-yakimovich requested changes
@Vik1975  Please take a look into new comments

2022-11-16 04:53 UTC, tatsiana-yakimovich commented on cypress/e2e/jScript_group.cy.js
> +        cy.url().should('eq','https://openweathermap.org/appid');
Don't add such check as it's a duplicate and already there one line below.
Also, don't delete empty lines in other tests as they were added on purpose to separate different parts

2022-11-16 04:55 UTC, Vik1975 commented on cypress/e2e/jScript_group.cy.js
> +        cy.url().should('eq','https://openweathermap.org/appid');
It is not my test you mentioned.

2022-11-16 04:56 UTC, Vik1975 commented on cypress/e2e/jScript_group.cy.js
> +        cy.url().should('eq','https://openweathermap.org/appid');
I think it was merging issue. I did AT 025_004 and AT 025_005 only

2022-11-16 04:59 UTC, Vik1975 commented on cypress/e2e/jScript_group.cy.js
> +        cy.url().should('eq','https://openweathermap.org/appid');
@tatsiana-yakimovich could you approve it please

2022-11-16 05:52 UTC, tatsiana-yakimovich commented on cypress/e2e/jScript_group.cy.js
> +        cy.url().should('eq','https://openweathermap.org/appid');
@Vik1975 we can't merge it in current state as you are changing someone's else tests which is not correct.
Not sure whether you are looking at the right place - just switch into "File changed" tab and review changes

2022-11-17 19:12 UTC, closed without merging