AT_010.008 | Marketplace > Verify the link "History Bulk” on the page
RedRoverSchool/OpenWeatherJS_05 pull request #219
Opened 2022-11-17 04:49 UTC by mcani

[AT_010.008 | Marketplace > Verify the link "History Bulk” on the page](https://trello.com/c/3nRej1yh/447-at010008-marketplace-verify-the-link-history-bulk-on-the-page)

2022-11-17 05:31 UTC, tatsiana-yakimovich requested changes

2022-11-17 05:31 UTC, tatsiana-yakimovich commented on cypress/e2e/jScript_group.cy.js
> +        cy.get('div#desktop-menu a[href*="marketplace"]').invoke('removeAttr', 'target').click()
340 and 341 lines are duplicated.
All commands are ended with ;

2022-11-18 02:17 UTC, tatsiana-yakimovich approved these changes
approved

2022-11-19 03:49 UTC, shabaiev submitted a review, later dismissed

2022-11-20 03:03 UTC, SvetlanaKanel approved these changes

2022-11-20 03:19 UTC, oxangyal approved these changes
good!

2022-11-20 03:31 UTC, merged