AT_014.003  Support > Ask a question>Verify if the "Ask the question" page open
RedRoverSchool/OpenWeatherJS_05 pull request #279
Opened 2022-11-18 21:00 UTC by PrimaMicher

https://trello.com/c/0jgPalZ5/556-at014003-support-ask-a-questionverify-if-the-ask-the-question-page-opens

2022-11-18 21:39 UTC, MariaMoroz requested changes
Один PR = одна задача или один тест

2022-11-18 22:39 UTC, MariaMoroz approved these changes

2022-11-18 22:39 UTC, MariaMoroz commented on cypress/e2e/jScript_group.cy.js
> +        cy.viewport(1280, 660)
cy.viewport(1280, 660) Это вам зачем? У нас в настройках все прописано, удалите пожалуйста отсюда эту строчку

2022-11-20 10:12 UTC, TimothyHuxx approved these changes
Approved

2022-11-20 15:00 UTC, MariaMoroz approved these changes

2022-11-20 15:08 UTC, merged