RF | arkGroup > AT_045.005
RedRoverSchool/OpenWeatherJS_05 pull request #325
Opened 2022-11-21 23:07 UTC by StanislavBliss

https://trello.com/c/BjtXAEVQ/704-rf-arkgroup-at045005-main-page-section-with-8-day-forecast-check-display-of-eight-days-from-current-date

2022-11-21 23:50 UTC, elviraKh1 commented on cypress/e2e/arkGroup.cy.js
> +  it.only('AT_045.005 | Main page > Section with 8-day forecast. Check display of eight days from current date', function () {
You have forgotten to change it.only in it

2022-11-22 04:58 UTC, MariaMoroz requested changes
к сожалению, пока не поправите выше сделанное замечание, пропустить этот пиар нельзя

2022-11-22 05:04 UTC, Penshin approved these changes

2022-11-22 09:59 UTC, StanislavBliss commented on cypress/e2e/arkGroup.cy.js
> +  it.only('AT_045.005 | Main page > Section with 8-day forecast. Check display of eight days from current date', function () {
oh.. thanks

2022-11-22 18:09 UTC, MariaMoroz commented on cypress/e2e/arkGroup.cy.js
> +/// <reference types="cypress" />
в папку e2e с сегодняшнего дня мы пишем только тесты в POM. Остальные тесты у нас находятся в папке OLD

2022-11-27 11:18 UTC, closed without merging