RF | About us > Verify "Buy by Subscription" button redirects to subscriptions page
RedRoverSchool/OpenWeatherJS_05 pull request #445
Opened 2022-11-28 18:26 UTC by Forostinko

https://trello.com/c/4DsWL9f1/824-rf-about-us-verify-buy-by-subscription-button-redirects-to-subscriptions-page

2022-11-28 18:57 UTC, EkaterinaRomankova submitted a review, later dismissed

2022-11-28 19:30 UTC, alena-resh submitted a review, later dismissed

2022-11-28 20:01 UTC, MariaMoroz commented on cypress/e2e/aboutUsPageSpec.cy.js
>      })
Зачем такое ожидание здесь добавлено?

2022-11-28 20:03 UTC, MariaMoroz requested changes

2022-11-28 20:03 UTC, MariaMoroz commented on cypress/fixtures/bugHunters.json
login credentials должны храниться в одном месте: а именно в fixture signInPage.json

2022-11-28 20:33 UTC, irinadash approved these changes

2022-11-29 04:36 UTC, 08AlimDuiL approved these changes

2022-11-30 18:44 UTC, MariaMoroz approved these changes

2022-11-30 19:43 UTC, alena-resh approved these changes

2022-11-30 22:09 UTC, merged