RF | 005.003 | Main page > Verifying the website's name and description
RedRoverSchool/OpenWeatherJS_05 pull request #501
Opened 2022-11-30 21:15 UTC by Massik78

https://trello.com/c/JgV6eOyN/883-rf-005003-main-page-verifying-the-websites-name-and-description

2022-11-30 21:16 UTC, Massik78 commented
![](https://github.trello.services/images/mini-trello-icon.png) [RF | 005.003 | Main page > Verifying the website's name and description](https://trello.com/c/JgV6eOyN/883-rf-005003-main-page-verifying-the-websites-name-and-description)

2022-11-30 21:22 UTC, nat-belyaeva submitted a review, later dismissed

2022-11-30 22:05 UTC, MariaMoroz requested changes
Уже создан класс TopicPage, где находится Home link.

2022-11-30 22:05 UTC, MariaMoroz commented on cypress/pageObjects/MainPage.js
> +        getHomePageButton: () => cy.get('.breadcrumb a[href="/"]'),
этого элемента нет на MainPage

2022-11-30 22:24 UTC, Massik78 commented on cypress/pageObjects/MainPage.js
> +        getHomePageButton: () => cy.get('.breadcrumb a[href="/"]'),
А это не мой элемент, его добавили до меня. Я вносил изменения только в 7ю и 10ю строки

2022-11-30 22:35 UTC, MariaMoroz commented on cypress/pageObjects/MainPage.js
> +        getHomePageButton: () => cy.get('.breadcrumb a[href="/"]'),
Это не так) в main этого элемента нет, а + означает, что добавлен он в этом пиаре

2022-11-30 22:37 UTC, MariaMoroz commented on cypress/pageObjects/MainPage.js
> +        getHomePageButton: () => cy.get('.breadcrumb a[href="/"]'),
я вижу, что вы его не используете в своем тесте, но он как-то появился в вашем пиаре)) надо убрать

2022-11-30 22:38 UTC, MariaMoroz commented on cypress/pageObjects/MainPage.js
> +        getHomePageButton: () => cy.get('.breadcrumb a[href="/"]'),
попробуйте обновить ветку, видимо, когда вы писали свой код, элемент был, а сейчас его там уже нет

2022-12-01 22:04 UTC, Massik78 reviewed
I have made all changes

2022-12-02 01:13 UTC, npkazakova approved these changes

2022-12-02 01:17 UTC, Massik78 commented on cypress/pageObjects/MainPage.js
> +        getHomePageButton: () => cy.get('.breadcrumb a[href="/"]'),
> попробуйте обновить ветку, видимо, когда вы писали свой код, элемент был, а сейчас его там уже нет

Маша, проверьте пожалуйста мой PR.

2022-12-02 01:38 UTC, alenakhan approved these changes

2022-12-02 03:47 UTC, MariaMoroz approved these changes

2022-12-02 06:52 UTC, merged