RF | guidePageSpec > AT_008.006.02 > Verify The text "OpenWeather products" is displayed
RedRoverSchool/OpenWeatherJS_05 pull request #567
Opened 2022-12-02 19:11 UTC by ElviraAvshalumov

https://trello.com/c/6ntKW5EZ/961-rf-guidepagespec-at00800602-main-menu-guide-verify-the-text-openweather-products-is-displayed

2022-12-02 19:11 UTC, ElviraAvshalumov commented
![](https://github.trello.services/images/mini-trello-icon.png) [RF | guidePageSpec > AT_008.006.02 > Verify The text "OpenWeather products" is displayed](https://trello.com/c/6ntKW5EZ/961-rf-guidepagespec-at00800602-verify-the-text-openweather-products-is-displayed)

2022-12-02 19:55 UTC, mznyerz approved these changes

2022-12-02 20:07 UTC, MariaMoroz requested changes
1.Вы тестируете header, значит тест должен находиться в header.Spec
2.Вы переходите на страницу Guide, значит должны сверить заголовок страницы "Guide"

2022-12-02 21:48 UTC, irinadash approved these changes

2022-12-04 20:16 UTC, irinadash approved these changes

2022-12-06 00:04 UTC, closed without merging