add new test
RedRoverSchool/OpenWeatherJS_05 pull request #63
Opened 2022-11-12 21:24 UTC by SvetlanaKanel

https://trello.com/c/yWi4jik2/274-at012004-partners-cms-verify-view-widget-button

2022-11-12 21:45 UTC, TimothyHuxx requested changes
Please name your PR according to the requirements. Instead of 'add new test #63' should be  'AT_012.004 | Partners > CMS > Verify "View widget" button'

2022-11-13 01:37 UTC, LIliia149 approved these changes
Approved

2022-11-13 01:54 UTC, MariaMoroz approved these changes

2022-11-13 02:36 UTC, TimothyHuxx approved these changes
Approved

2022-11-13 02:38 UTC, merged